# Jekyll configuration

name: 'Research Software Engineering Group'
description: rse.group.cam.ac.uk

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

permalink: /:year/:month/:title
# paginate: 3

highlighter: rouge
markdown: kramdown
# gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE', '*.py']
encoding: utf-8
